### ISSUE TITLE
Repair: call log section doesn't show any numbers

### ISSUE THREAD

**Issue by Termitebug** [omnight/phonehook#71]
Call Log is empty and not showing occurred numbers of answered/missed/called calls. I have Sony H4493 with 3.4 OS.

**Comment by jussijjj** [comment]
I also have this same issue. Also phonehook searches numbers that are in my contact list.  I am using Sony XA2.
This bug is caused because after SailfishX flashing the device has a username "defaultuser".
I made symbolic links from /home/defaultuser/.local/share to:
("/home/nemo/.local/share/system/Contacts/qtcontacts-sqlite/contacts.db");
("/home/nemo/.local/share/commhistory/commhistory.db");
Now I can see the call log and phonehook does not search when the number is in my contact list.

**Comment by arminfelder** [comment]
@jussijjj  hmm yes, this logic should refactored, but I don't know when I will mange to find some time for that
